name: myenv
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - pandas=1.4.3
  - numpy=1.23.1
  - scipy=1.8.1
  - scikit-learn=1.1.1
  - tensorflow=2.9.1
  - keras=2.9.0
  - pytorch=1.12.0
  - torchvision=0.13.0
  - nltk=3.7
  - spacy=3.4.0
  - transformers=4.20.1
  - opencv=4.6.0
  - pillow=9.2.0
  - matplotlib=3.5.2
  - seaborn=0.11.2
  - plotly=5.9.0
  - requests=2.28.1
  - beautifulsoup4=4.11.1
  - scikit-image=0.19.3
  - pytorch-lightning=1.6.5
  - tqdm=4.64.0
  - joblib=1.1.0
  - h5py=3.7.0
  - pickle5=0.0.12
